// src/lib/redux/mockHandlers.ts
// Mock data basada 1:1 en tu schema SQL
// Cuando el backend esté listo, simplemente eliminás este archivo
// y RTK Query apuntará a los endpoints reales

import type { ProductoAPI, EmpresaAPI, CategoriaAPI } from './api/types'

export const mockEmpresas: EmpresaAPI[] = [
  {
    id: 1,
    nombre: 'Tucu Moda Urbana',
    cuit: '20-12345678-9',
    whatsapp_contacto: '543815550011',
    sitio_web: 'https://tucumoda.com.ar',
    logo_url: null,
    banner_url: null,
    direccion: 'Peatonal Mendoza 100, SM de Tucumán',
    latitud: -26.8286,
    longitud: -65.2025,
    visible: true,
    activo: true,
    fecha_creacion: '2026-04-13T15:03:35Z',
  },
  {
    id: 2,
    nombre: 'Tecno Tucumán',
    cuit: '30-98765432-1',
    whatsapp_contacto: '543815550022',
    sitio_web: 'https://tecnotuc.com.ar',
    logo_url: null,
    banner_url: null,
    direccion: 'Av. Aconquija 2000, Yerba Buena',
    latitud: -26.8166,
    longitud: -65.2833,
    visible: true,
    activo: true,
    fecha_creacion: '2026-04-13T15:03:35Z',
  },
]

export const mockCategorias: CategoriaAPI[] = [
  { id: 1, nombre: 'Indumentaria', slug: 'indumentaria', visible: true, activo: true },
  { id: 2, nombre: 'Tecnología', slug: 'tecnologia', visible: true, activo: true },
  { id: 3, nombre: 'Deporte', slug: 'deporte', visible: true, activo: true },
  { id: 4, nombre: 'Hogar', slug: 'hogar', visible: true, activo: true },
]

export const mockProductos: ProductoAPI[] = [
  {
    id: 1,
    empresa_id: 1,
    categoria_id: 1,
    nombre: 'Remera Polo Manga Corta Slim Fit Transpirable',
    descripcion: 'Material 100% algodón premium, ideal para el calor tucumano. Disponible en talle S al XXL.',
    precio: 7500,
    precio_oferta: 6375,
    es_oferta: true,
    imagen_principal_url: 'https://placehold.co/400x400/0a2a4a/00aaff?text=Polo+Shirt',
    visible: true,
    activo: true,
    fecha_creacion: '2026-04-13T15:03:35Z',
    slug: 'remera-polo-manga-corta-slim-fit',
    empresa: mockEmpresas[0],
    categoria: mockCategorias[0],
  },
  {
    id: 2,
    empresa_id: 1,
    categoria_id: 1,
    nombre: 'Remera Blanca Cropped Cuello Redondo Heavyweight',
    descripcion: 'Corte oversize, tela pesada 220g. Perfecta para streetwear.',
    precio: 12900,
    precio_oferta: null,
    es_oferta: false,
    imagen_principal_url: 'https://placehold.co/400x400/f0f8ff/0066cc?text=White+Tee',
    visible: true,
    activo: true,
    fecha_creacion: '2026-04-13T15:03:35Z',
    slug: 'remera-blanca-cropped-heavyweight',
    empresa: mockEmpresas[0],
    categoria: mockCategorias[0],
  },
  {
    id: 3,
    empresa_id: 2,
    categoria_id: 2,
    nombre: 'Auriculares Bluetooth Premium Over-Ear',
    descripcion: 'Cancelación de ruido activa, 30hs de batería. Compatible con todos los dispositivos.',
    precio: 45000,
    precio_oferta: 38250,
    es_oferta: true,
    imagen_principal_url: 'https://placehold.co/400x400/001a33/00aaff?text=Headphones',
    visible: true,
    activo: true,
    fecha_creacion: '2026-04-14T10:00:00Z',
    slug: 'auriculares-bluetooth-premium-over-ear',
    empresa: mockEmpresas[1],
    categoria: mockCategorias[1],
  },
  {
    id: 4,
    empresa_id: 2,
    categoria_id: 2,
    nombre: 'Cargador Inalámbrico 15W MagSafe Compatible',
    descripcion: 'Carga rápida para iPhone y Android. Base de aluminio antideslizante.',
    precio: 18500,
    precio_oferta: null,
    es_oferta: false,
    imagen_principal_url: 'https://placehold.co/400x400/1a1a2e/4da6ff?text=Charger',
    visible: true,
    activo: true,
    fecha_creacion: '2026-04-15T08:00:00Z',
    slug: 'cargador-inalambrico-15w',
    empresa: mockEmpresas[1],
    categoria: mockCategorias[1],
  },
]